name: typos

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions: {}

defaults:
  run:
    shell: bash

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  check:
    name: typos
    runs-on: [self-hosted, Linux, X64, noctalia-appmenu]
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: crate-ci/typos@5c4feb79c242f07ca644aeca31aa4292e0b85fe4 # v1.45.2
        with:
          config: typos.toml
