name: typos

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions: {}

defaults:
  run:
    shell: bash

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  check:
    name: typos
    runs-on: [self-hosted, Linux, X64, noctalia-appmenu]
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: crate-ci/typos@7c572958218557a3272c2d6719629443b5cc26fd # v1.45.2
        with:
          config: typos.toml
